name: Update Years in README

on:
  schedule:
    - cron: "0 0 1 1 *"  # Runs at midnight on January 1st every year
  workflow_dispatch:  # Allows manual workflow trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Years and Update README
        run: |
          # Define the year the project started
          START_YEAR=2015

          # Get the current year
          CURRENT_YEAR=$(date +'%Y')

          # Calculate the number of years
          YEARS=$((CURRENT_YEAR - START_YEAR))

          echo "Updating README with $YEARS years..."

          # Replace the placeholder {{ YEARS }} in README.md with the calculated value
          sed -i "s/{{ YEARS }}/$YEARS/g" README.md

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the stored GitHub token
        run: |
          # Configure Git with the GitHub Actions bot user info
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the README file
          git add README.md

          # Commit the changes
          git commit -m "Update years to $YEARS years"

          # Push the changes back to the repository using the token
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
